### PR TITLE
add settings to control min and max terminal width

### LINKED ISSUE #81: Change column width
Is there any way to change column width when lines is long?
I tried using sublime settings but it looks i can't change
line width easily
when switching to monitor with higher resolution i can get longer lines
but i would like to just set it so if i want just enabling word wrap
instead wrapping always based on windows size

### PR DESCRIPTION
**Pull request by monkape**
Based on the discussion in #32 

I also added the `max_columns` setting that closes #81 if you find it useful. A ruler is shown at the max column.

Please let me know if you're ok with the `max_columns` and ruler bits, or if I should change anything else.

### CODE REVIEW

**Comment by monkape** [comment]
Setting min and max to the same number sets the terminal width independently of sublime's view:

fdsaffdsaf

**Comment by randy3k** [comment]
Thanks. Sorry for the late reply. Mind putting the settings in `Terminus.sublime-settings`? I'll merge the PR once it is done.

**Comment by monkape** [comment]
The settings already were in `Terminus.sublime-settings`, maybe you were looking at a wrong branch.

Anyway I pulled the upstream commit while at it.

**Comment by randy3k** [comment]
Oh my bad.

**Pull request merged**
