### PR TITLE
Expand `default_title` and `title`

### PR DESCRIPTION
**Pull request by mataha**
Self-explanatory; fulfills #373, probably #274 and #307 as well.

### CODE REVIEW

**Comment by Klaster1** [comment]
@randy3k any plans to merge the PR?

**Review by randy3k — APPROVED** [review]

**Comment by mataha** [comment]
Thanks!

**Comment by alofting** [comment]
How do I get back the short default titles rather than the full path? 'Titlte' does not seem to be recognized in shell configs.

And, R command inputs have suddenly inverted colors? Is this related?

This with Sublime Text on Windows. This changed after restarting machine today.

**Comment by randy3k** [comment]
Set 256 color by default 9d17345

**Comment by randy3k** [comment]
@alofting 
actually setting 256 color is not enough. It turns out that [prompt-toolkit](https://github.com/prompt-toolkit/python-prompt-toolkit/blob/669541123c9a72da1fda662cbd0a18ffe9e6d113/src/prompt_toolkit/output/windows10.py#L100) (radian dependency) assumes that the terminal supports true color (24 bit). However, Terminus only supports 8bit colors.
 
A solution is to pass the argument `env = {"PROMPT_TOOLKIT_COLOR_DEPTH": "DEPTH_8_BIT"}` in `terminus_open`.

**Comment by randy3k** [comment]
3d59b85 forces prompt-toolkit to use 256 color.

**Comment by alofting** [comment]
Finally more colors on Terminus for Windows 😄 - I can now revert to the default palette.

I now use these settings:

```JSON
  "256color": true,
  "unix_term": "xterm-256color",
```
I made this command that works fine to get a short title (and saving me some keystrokes when opening R in terminus as a bonus):

```JSON
[
    {
        "caption": "Terminus: Open Radian in Tab",
        "command": "terminus_open",
        "args": {
            "config_name": "R 4.4.0",
            "title": "R 4.4.0",
            "show_in_panel": false
        }
    }
]
```
I tried to be clever and reference the config_name parameter with
```JSON
"title": "${config_name}"
``` 
but that did not work.

Back to my original question; why does the title now default to the full path of the command?
```JSON
    {
      "name": "R 4.4.0",
      "cmd": ["c:\\Users\\alo\\AppData\\Local\\Continuum\\miniconda3\\envs\\radian\\Scripts\\radian.exe", "--r-binary=C:\\Users\\alo\\AppData\\Local\\Programs\\R\\R-4.4.0\\bin\\x64\\R.exe"],
      "enable": true,
      "env": {},
      "platforms": ["windows"],
    },
```

**Comment by randy3k** [comment]
We are now using a newer version of [pywinpty](https://github.com/andfoy/pywinpty) that uses ConPTY. I guess it handles the tty title differently.

**Comment by alofting** [comment]
Thanks, that explains why it has not changed on macOS when I test it there. Anyway, using the above command gave me control of the title and proved to be a faster way to create new R instances (which I do quite often). Getting more colors was great! 👍

**Comment by alofting** [comment]
I still get inverted text for many commands and constants: TRUE/FALSE, NA, source, library, function in Terminus with Radian with settings from above.

**Comment by randy3k** [comment]
Did you upgrade Terminus?
Or trying to regenerate the Terminus theme?

**Comment by alofting** [comment]
All light colors are shown as inverted text (light_cyan for constants, light_red for some commands such as `source`). Changing the settings as you suggested (shown below) only fixed the regular colors.

It is the same for all themes.

When I call 'Terminus Utilities: Remove User Theme' I get the following error:

image

All colors are gone. When call 'Terminus Utilities: Generate User Theme' then my user theme works again, but it does not fix the light colors.

I am on version 0.3.35. I have these settings:

```JSON
  "theme": "user", //"user", //"monokai-soda",
  "256color": true,
  "unix_term": "xterm-256color",

  "user_theme_colors": {
      "foreground": "#F8F8F2",
      "background": "#22262A", // "#22262A", //"#272822" ,
      "caret": "white",
      "block_caret": "white",
      "selection": "#444444",
      "selection_foreground": "#ffffff",
      "black": "#22262A",
      "red": "#f92672",
      "green": "#a6e22e",
      "brown": "#f4bf75", //"hsl(32, 98%, 65%)", // "#f4bf75",
      "blue": "#66d9ef",
      "magenta": "#ae81ff", //"hsl(338, 95%, 56%)", //"#ae81ff",
      "cyan": "#67d8ef",
      "white": "#f8f8f2",
      "light_black": "#75715e",
      "light_red": "#f92672",
      "light_green": "#a6e22e",
      "light_brown": "#f4bf75",
      "light_blue": "#66d9ef",
      "light_magenta": "#ae81ff",
      "light_cyan": "#67d8ef", //"#67d8ef", //"#a1efe4",
      "light_white": "#f9f8f5",
  }
```

I use this command for starting R in Radian

```JSON
    {
        "caption": "Terminus: Open Radian in Tab",
        "command": "terminus_open",
        "args": {
            "config_name": "R 4.4.1",
            "title": "R 4.4.1",
            "show_in_panel": false,
            "env": { 
                "prompt_toolkit_color_depth": "depth_8_bit"
            }
        }
    }
```

**Comment by randy3k** [comment]
Do you have bash installed in your Windows? Try running 
```
echo -e "\033[0;31mHello World\033[0m"   # red
echo -e "\033[1;31mHello World\033[0m"   # light red
```
to see if they produce expected result.
PS: the color for red and light_red are both "#f92672" in your user theme.

**Comment by alofting** [comment]
I have Git Bash:

image

Radian colors work fine in cmd and WezTerm on my Windows installation. But I SendCode 

The identical red and light red color code is probably leftover from earlier Terminus versions where at least some of the light colors got mapped to entirely different colors in what seemed to be a very limited palette.

**Comment by randy3k** [comment]
I actually meant running bash inside Terminus to test if colors are printed correctly.

**Comment by alofting** [comment]
Oh, like this?

image

The output colors are identical in this case.

**Comment by alofting** [comment]
image
 
 after changing user theme: `"light_red": "#ff0000"`

**Comment by randy3k** [comment]
It seems the color is working fine.

**Comment by alofting** [comment]
Yes, but not in Radian

image

**Comment by alofting** [comment]
It is the latest

image

**Pull request merged**
